services:
  - type: web
    name: tracking-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:5000 app:app"
    plan: free
    region: oregon
